# Generated by Django 6.0.4 on 2026-04-13 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        ("deals", "0001_initial"),
        ("leads", "0002_default_workflow_stages"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="tytul")),
                ("description", models.TextField(blank=True, verbose_name="opis")),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("TELEFON", "Telefon"),
                            ("EMAIL", "E-mail"),
                            ("SPOTKANIE", "Spotkanie"),
                            ("ZADANIE", "Zadanie"),
                            ("INNE", "Inne"),
                        ],
                        default="ZADANIE",
                        max_length=20,
                        verbose_name="typ",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("NISKI", "Niski"),
                            ("SREDNI", "Sredni"),
                            ("WYSOKI", "Wysoki"),
                            ("PILNY", "Pilny"),
                        ],
                        default="SREDNI",
                        max_length=10,
                        verbose_name="priorytet",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DO_ZROBIENIA", "Do zrobienia"),
                            ("W_TOKU", "W toku"),
                            ("WYKONANE", "Wykonane"),
                            ("ANULOWANE", "Anulowane"),
                        ],
                        default="DO_ZROBIENIA",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("due_date", models.DateTimeField(verbose_name="termin wykonania")),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Ustawiana automatycznie przy oznaczeniu jako wykonane.",
                        null=True,
                        verbose_name="data wykonania",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data utworzenia"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="data modyfikacji"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="przypisane do",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="companies.company",
                        verbose_name="firma",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utworzone przez",
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="deals.deal",
                        verbose_name="umowa",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="leads.lead",
                        verbose_name="lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "zadanie",
                "verbose_name_plural": "zadania",
                "ordering": ["due_date", "-priority"],
            },
        ),
    ]
