# Generated by Django 6.0.2 on 2026-04-20 13:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        ("deals", "0002_deal_deal_status_idx"),
        ("leads", "0003_lead_lead_status_idx_lead_lead_closed_at_idx"),
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["status"], name="task_status_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["due_date"], name="task_due_date_idx"),
        ),
    ]
