# Generated by Django 6.0.4 on 2026-04-13 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Pełna nazwa firmy lub imię i nazwisko klienta indywidualnego.",
                        max_length=200,
                        verbose_name="nazwa firmy",
                    ),
                ),
                (
                    "nip",
                    models.CharField(
                        blank=True,
                        help_text="Numer Identyfikacji Podatkowej (opcjonalny).",
                        max_length=20,
                        verbose_name="NIP",
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        choices=[
                            ("BUDOWNICTWO", "Budownictwo"),
                            ("IT", "IT / Technologia"),
                            ("HANDEL", "Handel"),
                            ("PRODUKCJA", "Produkcja"),
                            ("USLUGI", "Usługi"),
                            ("FINANSE", "Finanse / Ubezpieczenia"),
                            ("TRANSPORT", "Transport / Logistyka"),
                            ("ZDROWIE", "Zdrowie / Medycyna"),
                            ("EDUKACJA", "Edukacja"),
                            ("INNE", "Inne"),
                        ],
                        default="INNE",
                        max_length=20,
                        verbose_name="branża",
                    ),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=255, verbose_name="adres"),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="miasto"),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="kod pocztowy"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="telefon"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="e-mail"
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="strona www")),
                ("notes", models.TextField(blank=True, verbose_name="uwagi")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Odznacz aby zarchiwizować firmę bez usuwania danych.",
                        verbose_name="aktywna",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data dodania"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="data modyfikacji"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Handlowiec odpowiedzialny za tę firmę.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_companies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="opiekun handlowy",
                    ),
                ),
            ],
            options={
                "verbose_name": "firma",
                "verbose_name_plural": "firmy",
                "ordering": ["name"],
            },
        ),
    ]
