# Generated by Django 6.0.4 on 2026-04-13 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="imię")),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="nazwisko"),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="stanowisko"
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("ZARZAD", "Zarząd"),
                            ("SPRZEDAZ", "Sprzedaż"),
                            ("ZAKUPY", "Zakupy"),
                            ("IT", "IT"),
                            ("FINANSE", "Finanse / Księgowość"),
                            ("HR", "HR / Kadry"),
                            ("MARKETING", "Marketing"),
                            ("PRODUKCJA", "Produkcja"),
                            ("LOGISTYKA", "Logistyka"),
                            ("INNE", "Inne"),
                        ],
                        default="INNE",
                        max_length=20,
                        verbose_name="dział",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="e-mail"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="telefon"),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="telefon komórkowy"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="uwagi")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Odznacz aby zarchiwizować kontakt bez usuwania.",
                        verbose_name="aktywny",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data dodania"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="data modyfikacji"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Firma, w której pracuje ta osoba.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="companies.company",
                        verbose_name="firma",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_contacts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="opiekun handlowy",
                    ),
                ),
            ],
            options={
                "verbose_name": "kontakt",
                "verbose_name_plural": "kontakty",
                "ordering": ["last_name", "first_name"],
            },
        ),
    ]
