# Generated by Django 6.0.4 on 2026-04-13 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        ("contacts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="nazwa etapu"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Niższy numer = wcześniej na tablicy Kanban.",
                        verbose_name="kolejność",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#6c757d",
                        help_text="Kolor hex kolumny Kanban, np. #28a745.",
                        max_length=7,
                        verbose_name="kolor",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="aktywny"),
                ),
            ],
            options={
                "verbose_name": "etap lejka",
                "verbose_name_plural": "etapy lejka",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Krótki opis okazji sprzedażowej.",
                        max_length=200,
                        verbose_name="tytuł",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOWY", "Nowy"),
                            ("W_TOKU", "W toku"),
                            ("WYGRANA", "Wygrana"),
                            ("PRZEGRANA", "Przegrana"),
                            ("ANULOWANY", "Anulowany"),
                        ],
                        default="NOWY",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("FORMULARZ", "Formularz www"),
                            ("POLECENIE", "Polecenie"),
                            ("COLD_CALL", "Cold call"),
                            ("KAMPANIA", "Kampania marketingowa"),
                            ("TARGI", "Targi / Wydarzenie"),
                            ("INNE", "Inne"),
                        ],
                        default="INNE",
                        max_length=20,
                        verbose_name="źródło",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Szacowana wartość transakcji w złotych.",
                        max_digits=12,
                        verbose_name="wartość (PLN)",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="opis")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data utworzenia"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="data modyfikacji"
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Ustawiana automatycznie przy wygranej lub przegranej.",
                        null=True,
                        verbose_name="data zamknięcia",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leads",
                        to="companies.company",
                        verbose_name="firma",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="contacts.contact",
                        verbose_name="kontakt",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_leads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="handlowiec",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        help_text="Aktualny etap na tablicy Kanban.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leads",
                        to="leads.workflowstage",
                        verbose_name="etap",
                    ),
                ),
            ],
            options={
                "verbose_name": "lead",
                "verbose_name_plural": "leady",
                "ordering": ["-created_at"],
            },
        ),
    ]
