# Generated by Django 6.0.4 on 2026-04-13 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        ("deals", "0001_initial"),
        ("leads", "0002_default_workflow_stages"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="tytul dokumentu"),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("OFERTA", "Oferta"),
                            ("UMOWA", "Umowa"),
                            ("PROTOKOL", "Protokol odbioru"),
                            ("FAKTURA", "Faktura"),
                            ("INNY", "Inny"),
                        ],
                        default="INNY",
                        max_length=20,
                        verbose_name="rodzaj dokumentu",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Dozwolone formaty: PDF, DOCX, XLSX, JPG, PNG.",
                        upload_to="documents/%Y/%m/",
                        verbose_name="plik",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="opis")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data wgrania"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="data modyfikacji"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="companies.company",
                        verbose_name="firma",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="wgrane przez",
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="deals.deal",
                        verbose_name="umowa",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="leads.lead",
                        verbose_name="lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "dokument",
                "verbose_name_plural": "dokumenty",
                "ordering": ["-created_at"],
            },
        ),
    ]
