# Generated by Django 6.0.4 on 2026-04-13 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        ("leads", "0002_default_workflow_stages"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="tytuł umowy")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AKTYWNA", "Aktywna"),
                            ("ZREALIZOWANA", "Zrealizowana"),
                            ("ANULOWANA", "Anulowana"),
                        ],
                        default="AKTYWNA",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Wartość umowy w złotych brutto.",
                        max_digits=12,
                        verbose_name="wartość (PLN)",
                    ),
                ),
                (
                    "signed_at",
                    models.DateField(
                        blank=True,
                        help_text="Ustawiana automatycznie przy zatwierdzeniu umowy.",
                        null=True,
                        verbose_name="data podpisania",
                    ),
                ),
                (
                    "close_date",
                    models.DateField(
                        help_text="Planowana data zamknięcia lub dostarczenia.",
                        verbose_name="termin realizacji",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="opis / warunki"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data utworzenia"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="data modyfikacji"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deals",
                        to="companies.company",
                        verbose_name="firma",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        help_text="Lead, z którego powstała ta umowa (opcjonalny).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deals",
                        to="leads.lead",
                        verbose_name="lead źródłowy",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_deals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="handlowiec",
                    ),
                ),
            ],
            options={
                "verbose_name": "umowa",
                "verbose_name_plural": "umowy",
                "ordering": ["-created_at"],
            },
        ),
    ]
