# Generated by Django 6.0.2 on 2026-04-20 13:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        ("deals", "0001_initial"),
        ("leads", "0002_default_workflow_stages"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(fields=["status"], name="deal_status_idx"),
        ),
    ]
