# Generated by Django 6.0.4 on 2026-04-14 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("UTWORZONO", "Utworzono"),
                            ("ZAKTUALIZOWANO", "Zaktualizowano"),
                            ("USUNIETO", "Usunieto"),
                            ("WYSWIETLONO", "Wyswietlono"),
                        ],
                        max_length=20,
                        verbose_name="akcja",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(max_length=100, verbose_name="nazwa modelu"),
                ),
                ("object_id", models.PositiveIntegerField(verbose_name="ID obiektu")),
                (
                    "object_repr",
                    models.CharField(
                        max_length=200, verbose_name="reprezentacja obiektu"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="opis")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="adres IP"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data zdarzenia"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="uzytkownik",
                    ),
                ),
            ],
            options={
                "verbose_name": "log aktywnosci",
                "verbose_name_plural": "logi aktywnosci",
                "ordering": ["-created_at"],
            },
        ),
    ]
