# Generated by Django 6.0.2 on 2026-04-20 13:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(fields=["action"], name="activitylog_action_idx"),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["created_at"], name="activitylog_created_at_idx"
            ),
        ),
    ]
